Stop if trying to copy to itself.

diff --git a/mtran b/mtran
--- a/mtran
+++ b/mtran
@@ -18,11 +18,12 @@ function F_MASS_TRANSFER()
   SRC_DIR=$(readlink -ev "${SRC_DIR}")
   DEST_DIR=$(readlink -ev "${DEST_DIR}")
   
-  # Stop if source and destination directory are the same.
-  if [ "${SRC_DIR}" = "${DEST_DIR}" ]; then echo "Error: Source and destination directory are the same. Aborted!"; exit 1; fi;
 
   SRC_BASE_DIR=$(dirname "${SRC_DIR}")
   SRC_DIR_NAME=$(basename "${SRC_DIR}")
+
+  # Stop if trying to copy to itself.
+  if [ "${SRC_BASE_DIR}" = "${DEST_DIR}" ]; then echo "Error: Trying to copy to itself. Aborted!"; exit 1; fi;
 
   ACTION=$(echo "${ACTION}" | tr '[:upper:]' '[:lower:]')  # Lowercase to avoid case typo.
   case "${ACTION}" in
